import type { TextureEntry } from './scanner';

/**
 * Generate a TypeScript source file with typed texture constants.
 * Output is deterministic (sorted by name) for stable diffs.
 */
export function generateAssetCode(entries: TextureEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [
    '// AUTO-GENERATED by vite-plugin-hyperion-assets — DO NOT EDIT',
    '',
    'export const Textures = {',
  ];

  for (const entry of sorted) {
    lines.push(
      `  ${entry.name}: { path: '${entry.path}', width: ${entry.width}, height: ${entry.height}, compressed: ${entry.compressed} },`,
    );
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export type TextureName = keyof typeof Textures;');
  lines.push('');

  return lines.join('\n');
}
